- Name: Registry
  Property:
    - Key: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      ValueName: HideFileExt
      ValueData: "0"
      ValueType: DWord
    - Key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa
      ValueName: DisableLoopbackCheck
      ValueData: "1"
      ValueType: DWord
# - Name: WindowsOptionalFeature
#   Property:
#     - Name: IIS-ApplicationDevelopment
#     - Name: IIS-ASPNET

# - Name: MyScoop
#   ModuleName: MyResources

# - Name: MyScoopPackage
#   ModuleName: MyResources
#   Property:
#     - PackageName: dotnet-sdk
#     - PackageName: gh

# - Name: MyChocolatey
#   ModuleName: MyResources

# - Name: MyChocolateyPackage
#   ModuleName: MyResources
#   Property:
#     - PackageName: 7zip
#     - PackageName: adobereader

# - Name: WinGetPackage
#   ModuleName: Microsoft.WinGet.DSC
#   Property:
#     - Id: Fork.Fork
#     - Id: Microsoft.PowerShell

# - Name: VSComponents
#   ModuleName: Microsoft.VisualStudio.DSC
#   Property:
#     - productId: Microsoft.VisualStudio.Product.Enterprise
#       channelId: VisualStudio.17.Release
#       vsConfigFile: C:\Projets\WaC\resources\visual-studio\.vsconfig
#       includeRecommended: true

# - Name: MyCertificate
#   ModuleName: MyResources
#   Property:
#     - Path: C:\Projets\WaC\resources\certificates\_.cr-paca.fr.crt
#     - Path: C:\Projets\WaC\resources\certificates\Autorite de Certification Region SUD Provence-Alpes-Cote d'Azur.crt

# - Name: MyWindowsDefenderExclusion
#   ModuleName: MyResources
#   Property:
#     - Type: Path
#       Value: C:\Projets
#     - Type: Path
#       Value: C:\Users\%user%\.dotnet\tools

# - Name: MyNodeVersion
#   ModuleName: MyResources
#   Property:
#     - Version: lts
#       Ensure: Used
#     - Version: 18

# - Name: MyHosts
#   ModuleName: MyResources
#   Property:
#     - Name: RÃ©gionSUD
#       Path: C:\Projets\WaC\resources\hosts
