$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/v3/bundled/config/document.json
resources:
- name: HideFileExt
  type: Microsoft.Windows/Registry
  properties:
    keyPath: HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    valueData:
      DWord: 0
    valueName: HideFileExt
- name: DisableLoopbackCheck
  type: Microsoft.Windows/Registry
  properties:
    keyPath: HKLM\SYSTEM\CurrentControlSet\Control\Lsa
    valueData:
      DWord: 1
    valueName: DisableLoopbackCheck
- name: MyScoop1
  type: MyScoop/MyScoop
  properties: {}
- name: dotnetsdk
  type: MyScoopPackage/MyScoopPackage
  properties:
    PackageName: dotnet-sdk
- name: gh
  type: MyScoopPackage/MyScoopPackage
  properties:
    PackageName: gh
- name: MyWindowsDefenderExclusion1
  type: MyWindowsDefenderExclusion/MyWindowsDefenderExclusion
  properties:
    Value: C:\Projets
    Type: Path
- name: MyWindowsDefenderExclusion2
  type: MyWindowsDefenderExclusion/MyWindowsDefenderExclusion
  properties:
    Value: C:\Users\%user%\.dotnet\tools
    Type: Path
- name: MyNodeVersion1
  type: MyNodeVersion/MyNodeVersion
  properties:
    Version: lts
    Ensure: Used
- name: MyNodeVersion2
  type: MyNodeVersion/MyNodeVersion
  properties:
    Version: 18
- name: RegionSUD
  type: MyHosts/MyHosts
  properties:
    Name: RegionSUD
    Path: C:\WaC\resources\hosts

